version: "3.3"

services:
  backend:
    build:
      ./server
    volumes:
      - ./server/db/:/yombo_server/db
    restart: unless-stopped
  nginx:
    build:
      ./frontend
    ports:
      - "3075:80"
    restart: unless-stopped
volumes:
  db:
